Repository CAU-DesignPattern-2024/rabbit-escape, pull requests merged in 2024-12, with the labels that each got.

#12 [feat] GithubIssue 클래스에 State 패턴 적용 (#11)
  run.sh
  src/ui-swing/src/rabbitescape/ui/swing/GitHubClient.java
  src/ui-swing/src/rabbitescape/ui/swing/GitHubIssue.java
  src/ui-swing/src/rabbitescape/ui/swing/state/BugIssueState.java
  src/ui-swing/src/rabbitescape/ui/swing/state/DefaultIssueState.java
  src/ui-swing/src/rabbitescape/ui/swing/state/IssueState.java
  src/ui-swing/src/rabbitescape/ui/swing/state/LevelIssueState.java
  src/ui-swing/test/rabbitescape/ui/swing/TestGitHubIssue.java
Labels: feat, test

#13 [feat] World 이벤트 관리에 Observer 패턴 적용
  src/engine/src/rabbitescape/engine/World.java
  src/engine/src/rabbitescape/engine/events/EventType.java
  src/engine/src/rabbitescape/engine/events/GameEvent.java
  src/engine/src/rabbitescape/engine/events/GameEventListener.java
  src/engine/src/rabbitescape/engine/events/GameEventManager.java
  src/engine/src/rabbitescape/engine/events/LevelWinEvent.java
  src/engine/src/rabbitescape/engine/events/LevelWinListenerAdapter.java
  src/engine/src/rabbitescape/engine/events/RabbitEvent.java
  src/engine/src/rabbitescape/engine/events/StatsChangedEvent.java
  src/engine/src/rabbitescape/engine/events/WorldStatsListenerAdapter.java
  src/engine/test/rabbitescape/engine/events/GameEventManagerTest.java
  src/engine/test/rabbitescape/engine/events/LevelWinListenerAdapterTest.java
  src/engine/test/rabbitescape/engine/events/TestGameEvent.java
Labels: feat

#15 [fix] #9 World 이벤트 관리 Observer 패턴 관련 Test Code 수정
  src/engine/src/rabbitescape/engine/mock/events/MockGameEvent.java
  src/engine/test/rabbitescape/engine/events/GameEventManagerTest.java
Labels: fix

#18 [feat] Visitor 패턴으로 로깅 기능 추가
  src/engine/src/rabbitescape/engine/BehaviourTools.java
  src/engine/src/rabbitescape/engine/Entrance.java
  src/engine/src/rabbitescape/engine/Exit.java
  src/engine/src/rabbitescape/engine/Fire.java
  src/engine/src/rabbitescape/engine/Pipe.java
  src/engine/src/rabbitescape/engine/Rabbit.java
  src/engine/src/rabbitescape/engine/Thing.java
  src/engine/src/rabbitescape/engine/ThingLogVisitor.java
  src/engine/src/rabbitescape/engine/ThingVisitor.java
  src/engine/src/rabbitescape/engine/Token.java
  src/engine/src/rabbitescape/engine/WaterRegion.java
Labels: feat

#22 [feat] Bridging 클래스에 Strategy 패턴 적용 (#19)
  src/engine/src/rabbitescape/engine/behaviours/Bridging.java
  src/engine/src/rabbitescape/engine/behaviours/bridge/BaseBridgingStrategy.java
  src/engine/src/rabbitescape/engine/behaviours/bridge/BridgingStrategy.java
  src/engine/src/rabbitescape/engine/behaviours/bridge/InCornerLeftBridgingStrategy.java
  src/engine/src/rabbitescape/engine/behaviours/bridge/InCornerRightBridgingStrategy.java
  src/engine/src/rabbitescape/engine/behaviours/bridge/InCornerUpLeftBridgingStrategy.java
  src/engine/src/rabbitescape/engine/behaviours/bridge/InCornerUpRightBridgingStrategy.java
  src/engine/src/rabbitescape/engine/behaviours/bridge/InitialAlongBridgingStrategy.java
  src/engine/src/rabbitescape/engine/behaviours/bridge/InitialDownUpBridgingStrategy.java
  src/engine/src/rabbitescape/engine/behaviours/bridge/InitialInCornerBridgingStrategy.java
  src/engine/src/rabbitescape/engine/behaviours/bridge/InitialUpBridgingStrategy.java
  src/engine/src/rabbitescape/engine/behaviours/bridge/LeftBridgingStrategy.java
  src/engine/src/rabbitescape/engine/behaviours/bridge/RightBridgingStrategy.java
  src/engine/src/rabbitescape/engine/behaviours/bridge/UpLeftBridgingStrategy.java
  src/engine/src/rabbitescape/engine/behaviours/bridge/UpRightBridgingStrategy.java
Labels: feat

#23 [fix] Strategy 패턴 적용 과정에서 오동작 수정
  src/engine/src/rabbitescape/engine/behaviours/Bridging.java
  src/engine/src/rabbitescape/engine/behaviours/bridge/BaseBridgingStrategy.java
  src/engine/src/rabbitescape/engine/behaviours/bridge/BridgeTypeProvider.java
  src/engine/src/rabbitescape/engine/behaviours/bridge/BridgingStrategy.java
  src/engine/src/rabbitescape/engine/behaviours/bridge/InitialAlongBridgingStrategy.java
  src/engine/src/rabbitescape/engine/behaviours/bridge/InitialDownUpBridgingStrategy.java
  src/engine/src/rabbitescape/engine/behaviours/bridge/InitialInCornerBridgingStrategy.java
  src/engine/src/rabbitescape/engine/behaviours/bridge/InitialUpBridgingStrategy.java
Labels: fix

#24 [feat] Token 클래스 Decorator 패턴 적용
  src/engine/src/rabbitescape/engine/BaseToken.java
  src/engine/src/rabbitescape/engine/TokenComponent.java
  src/engine/src/rabbitescape/engine/TokenDecorator.java
  src/engine/src/rabbitescape/engine/decorators/DurationDecorator.java
  src/engine/src/rabbitescape/engine/decorators/EnhancedRangeDecorator.java
  src/engine/src/rabbitescape/engine/decorators/SpecialEffectDecorator.java
  src/engine/test/rabbitescape/engine/decorators/TestTokenDecorators.java
Labels: feat

#29 [feat] Walking 클래스에 COR 패턴 적용
  .idea/misc.xml
  .idea/modules.xml
  src/engine/.project
  src/engine/src/rabbitescape/engine/behaviours/Walking.java
  src/engine/src/rabbitescape/engine/behaviours/walk/DownSlopeHandler.java
  src/engine/src/rabbitescape/engine/behaviours/walk/FlatGroundHandler.java
  src/engine/src/rabbitescape/engine/behaviours/walk/StateHandler.java
  src/engine/src/rabbitescape/engine/behaviours/walk/UpSlopeHandler.java
  src/render/.project
  src/ui-swing/.project
  src/ui-text/.project
Labels: feat

#31 [feat] WorldChanges 클래스에 Command 패턴 적용
  src/engine/src/rabbitescape/engine/World.java
  src/engine/src/rabbitescape/engine/behaviours/Bridging.java
  src/engine/src/rabbitescape/engine/commands/AddBlockCommand.java
  src/engine/src/rabbitescape/engine/commands/AddTokenCommand.java
  src/engine/src/rabbitescape/engine/commands/Command.java
  src/engine/src/rabbitescape/engine/commands/EnterRabbitCommand.java
  src/engine/src/rabbitescape/engine/commands/ExplodeAllCommand.java
  src/engine/src/rabbitescape/engine/commands/KillRabbitCommand.java
  src/engine/src/rabbitescape/engine/commands/RemoveBlockAtCommand.java
  src/engine/src/rabbitescape/engine/commands/RemoveFireCommand.java
  src/engine/src/rabbitescape/engine/commands/RemoveTokenCommand.java
  src/engine/src/rabbitescape/engine/commands/SaveRabbitCommand.java
  src/engine/src/rabbitescape/engine/commands/UndoableCommand.java
  src/engine/src/rabbitescape/engine/commands/WorldChangesWithCommand.java
  src/engine/test/rabbitescape/engine/util/TestUtil.java
Labels: feat

#30 [feat] Solution 패키지 내 Composite 패턴 적용
  src/engine/src/rabbitescape/engine/solution/ActionSerializer.java
  src/engine/src/rabbitescape/engine/solution/AssertStateAction.java
  src/engine/src/rabbitescape/engine/solution/CommandAction.java
  src/engine/src/rabbitescape/engine/solution/Component.java
  src/engine/src/rabbitescape/engine/solution/PlaceTokenAction.java
  src/engine/src/rabbitescape/engine/solution/SelectAction.java
  src/engine/src/rabbitescape/engine/solution/Solution.java
  src/engine/src/rabbitescape/engine/solution/SolutionCommand.java
  src/engine/src/rabbitescape/engine/solution/SolutionIgnorer.java
  src/engine/src/rabbitescape/engine/solution/SolutionInterpreter.java
  src/engine/src/rabbitescape/engine/solution/SolutionParser.java
  src/engine/src/rabbitescape/engine/solution/SolutionRecorder.java
  src/engine/src/rabbitescape/engine/solution/SolutionRecorderTemplate.java
  src/engine/src/rabbitescape/engine/solution/UntilAction.java
  src/engine/src/rabbitescape/engine/solution/ValidationAction.java
  src/engine/src/rabbitescape/engine/solution/WaitAction.java
  src/engine/test/rabbitescape/engine/solution/TestComposite.java
  src/engine/test/rabbitescape/engine/solution/TestSolutionParser.java
  src/ui-text/src/rabbitescape/ui/text/InputHandler.java
Labels: feat

#33 [fix] make 컴파일 에러 수정
  src/engine/src/rabbitescape/engine/WorldChanges.java
  src/engine/src/rabbitescape/engine/commands/RemoveBlockAtCommand.java
Labels: fix

#34 [fix] 불필요한 코드 제거 및 일부 재정비
  src/render/src/rabbitescape/render/AnimationCache.java
  src/render/test/rabbitescape/render/TestFrame.java
  src/ui-swing/src/rabbitescape/ui/swing/GitHubIssue.java
  src/ui-swing/src/rabbitescape/ui/swing/GitHubIssueDialog.java
  src/ui-swing/src/rabbitescape/ui/swing/state/BugIssueState.java
  src/ui-swing/src/rabbitescape/ui/swing/state/DefaultIssueState.java
  src/ui-swing/src/rabbitescape/ui/swing/state/LevelIssueState.java
  src/ui-swing/src/rabbitescape/ui/swing/state/StateUtil.java
  src/ui-swing/test/rabbitescape/ui/swing/TestGitHubIssue.java
Labels: fix, refactor

#35 [ hotfix] TestGithubIssue 잘못된 표현 수정
  src/ui-swing/test/rabbitescape/ui/swing/TestGitHubIssue.java
Labels: fix

#37 [FIX] WorldChange Command 패턴 관련 Test 불가
  src/engine/src/rabbitescape/engine/World.java
Labels: fix

#38 [test] Bridging 전략 패턴에 대한 테스트코드 작성
  src/engine/src/rabbitescape/engine/WorldChanges.java
  src/engine/test/rabbitescape/engine/logic/TestBridgingStrategies.java
Labels: test
